apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://6dfa62031f78f9b9a6719531c55e6827-3000.maxwell.assessments.scaler.com/john_doe/argocd-helm-chart.git
    targetRevision: main
    path: helm-chart
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
