apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP  # Ensures internal cluster-only access
