apiVersion: v2
name: jenkins-wrapper
description: A Helm chart that wraps the Jenkins Helm chart
version: 1.0.0
dependencies:
  - name: jenkins
    version: 5.7.8
    repository: "https://charts.jenkins.io"
