apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  labels:
    app: backend-app
spec:
  destination:
    namespace: backend-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-app/manifests
    repoURL: https://github.com/smartlizzard/sclass.git
    targetRevision: day-137-q13-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
